name: "Lock down repository"

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          exclude-issue-labels: "comment"
          close-issue: true
          lock-issue: true
          close-pr: true
          lock-pr: true
          pr-comment: "We do not accept PRs. If you have any questions, please feel free to contact us."
